/** @type {import('tailwindcss').Config} */
export default {
  content: ["./index.html", "./src/**/*.{js,ts,jsx,tsx}"],
  darkMode: "class",
  theme: {
    extend: {
      colors: {
        "surface-variant": "#353436",
        "on-background": "#e5e2e3",
        "inverse-primary": "#00696f",
        "on-primary-fixed": "#002022",
        "secondary-fixed-dim": "#2ae500",
        "surface-container-high": "#2a2a2b",
        "primary-container": "#00f2ff",
        "on-secondary-fixed": "#022100",
        "surface-container-lowest": "#0e0e0f",
        "inverse-on-surface": "#313031",
        "on-secondary-fixed-variant": "#095300",
        "on-secondary": "#053900",
        error: "#ffb4ab",
        "on-tertiary-container": "#c00042",
        "on-secondary-container": "#0f6d00",
        "on-surface-variant": "#b9cacb",
        "tertiary-fixed": "#ffd9dc",
        "surface-bright": "#3a393a",
        "surface-container": "#201f20",
        outline: "#849495",
        "on-tertiary-fixed-variant": "#910030",
        "tertiary-fixed-dim": "#ffb2ba",
        "on-error": "#690005",
        tertiary: "#fff5f5",
        "tertiary-container": "#ffcfd3",
        "primary-fixed-dim": "#00dbe7",
        "primary-fixed": "#74f5ff",
        background: "#131314",
        "surface-container-highest": "#353436",
        "secondary-container": "#2ff801",
        surface: "#131314",
        "on-primary": "#00363a",
        "surface-tint": "#00dbe7",
        primary: "#e1fdff",
        "error-container": "#93000a",
        "on-tertiary-fixed": "#400010",
        "outline-variant": "#3a494b",
        "on-surface": "#e5e2e3",
        "secondary-fixed": "#79ff5b",
        "surface-dim": "#131314",
        "on-primary-fixed-variant": "#004f54",
        secondary: "#d7ffc5",
        "on-primary-container": "#006a71",
        "on-error-container": "#ffdad6",
        "surface-container-low": "#1c1b1c",
        "on-tertiary": "#67001f",
        "inverse-surface": "#e5e2e3",
        "accent-purple": "#bf00ff",
      },
      borderRadius: {
        DEFAULT: "0.25rem",
        lg: "0.5rem",
        xl: "0.75rem",
        full: "9999px",
      },
      spacing: {
        unit: "4px",
        "stack-gap": "8px",
        gutter: "16px",
        margin: "24px",
        "panel-padding": "12px",
      },
      fontFamily: {
        "caption-xs": ["JetBrains Mono", "monospace"],
        "terminal-header": ["Space Grotesk", "sans-serif"],
        "data-mono-sm": ["JetBrains Mono", "monospace"],
        "data-mono-lg": ["JetBrains Mono", "monospace"],
        "data-mono-md": ["JetBrains Mono", "monospace"],
      },
      fontSize: {
        "caption-xs": ["10px", { lineHeight: "12px", letterSpacing: "0.1em", fontWeight: "700" }],
        "terminal-header": [
          "18px",
          { lineHeight: "24px", letterSpacing: "0.05em", fontWeight: "700" },
        ],
        "data-mono-sm": [
          "12px",
          { lineHeight: "16px", letterSpacing: "0.02em", fontWeight: "400" },
        ],
        "data-mono-lg": [
          "16px",
          { lineHeight: "24px", letterSpacing: "-0.02em", fontWeight: "500" },
        ],
        "data-mono-md": ["14px", { lineHeight: "20px", letterSpacing: "0em", fontWeight: "400" }],
      },
    },
  },
  plugins: [],
};
